### ISSUE TITLE
A simple example

### ISSUE THREAD

**Issue by aferust** [gilzoide/bettercmath#1]
I couldn't find any example in the code. Could you please include an example corresponding to:

from: https://learnopengl.com/In-Practice/2D-Game/Rendering-Sprites

```cpp
glm::mat4 model = glm::mat4(1.0f);
model = glm::translate(model, glm::vec3(position, 0.0f));  

model = glm::translate(model, glm::vec3(0.5f * size.x, 0.5f * size.y, 0.0f)); 
model = glm::rotate(model, glm::radians(rotate), glm::vec3(0.0f, 0.0f, 1.0f)); 
model = glm::translate(model, glm::vec3(-0.5f * size.x, -0.5f * size.y, 0.0f));
```

**Comment by aferust** [comment]
Ahh yes, I can do things like:

```d
const float[3] zeroTranslation = [0.5f * r.w, 0.5f * r.h, 0.0f];

alias Transform3D = Transform!(float, 3, false);
auto model = Transform3D();
model.translate(zeroTranslation);
model.rotate(angle);
```

**Comment by gilzoide** [comment]
Yeah, I still need to add examples, more unittests and documentation, sorry about that.

If you want, you can also chain the functions that mutate a Transform like `translate`, `rotate*` and `scale`:
```d
alias Transform3D = Transform!(float, 3);  // flag may be omitted for non-compact Transforms (I want to refactor this bool for an enum like `TransformOptions.compact` to make it more clear !!! breaking change alert !!!)
alias Vec3 = Vector!(float, 3);

auto zeroTranslation = Vec3(0.5 * r.w, 0.5 * r.h);
auto model = Transform3D()
    .translate(zeroTranslation)
    .rotateZDegrees(angleInDegrees)
    .translate(-zeroTranslation);
```

Also, rotations about arbitrary axes are not implemented yet, only rotating around the X, Y and Z axes, so maybe not all `glm::rotate` calls will be directly translatable for now.

**Comment by aferust** [comment]
Ok, I see. My chipmunk physics provides angles for sprite bodies:

angle = cpBodyGetAngle(_body);

I want to apply this rotation to rendering. Looks like I cannot do it with bettercmath yet?

**Comment by gilzoide** [comment]
Yes, you can apply rotations to Transforms, as long as they are around one of the X, Y or Z axes with `rotateX`, `rotateY`, `rotateZ` or `rotate` (rotating in 2D is the same as rotating around the Z axis on 3D transformations).
For now, you can rotate along more than one axis by concatenating rotations:
```d
auto model = Transform3D()
    .rotateX(angleX)
    .rotateY(angleY)
    .rotateZ(angleZ);
```

What I meant about rotating around arbitrary axes is like `glm::rotate` where you pass a `vec3` with the axis vector, this I didn't implement yet.

For Chipmunk bodies, you can apply the  translation and rotation, no problem:
```d
// WARNING: this code is wrong, see answer below
auto model = Transform3D()
    .translate(cpBodyGetPosition(_body))
    .rotate(cpBodyGetAngle(_body));
```
Just remember that the transformation order matters, translating first and then rotating will probably give different results than rotating first and then translating.

**Comment by gilzoide** [comment]
@aferust I just realised I reversed the transformation order, even after writing that you should take care about it, sorry

Here is a version that should do the right thing: first rotate around the body's center of mass, then move it to the right position
```d
auto model = Transform3D()
    .translate(-cpBodyGetCenterOfGravity(_body))  // this moves the center of gravity to origin...
    .rotate(cpBodyGetAngle(_body))  // ...so that the rotation is applied around that point
    .translate(cpBodyGetPosition(_body));  // after rotating around center of gravity, move to the right position
```
